Searching
pinnheads/DSA pull request #1
Opened 2022-01-11 05:26 UTC by pinnheads

- [x] Linear Search
- [ ] Binary Search

2022-01-22 18:52 UTC, avinash-rath commented on Algo/Search/search.py
> +    beg, end = 0, len(arr) - 1
beg is good, can you come up with a better name?

2022-01-22 18:53 UTC, avinash-rath commented on Algo/Search/search.py
> +
[nit] remove extra line

2022-01-23 09:52 UTC, avinash-rath requested changes

2022-01-23 09:52 UTC, avinash-rath commented on DS/linked_list.py
> +        raise Exception("Node with data '%s' not found" % target_node_data)
Both methods are nice to have. However, from a library point of view, it's better to implement just `insert(index, node)` method which inserts one node at position `index`.

e.g.
```
myNode: 1->2->3
// myNode.insert(1, Node(5));
myNode: 1->5->2->3
```

2022-01-23 09:52 UTC, avinash-rath commented on DS/linked_list.py
> +    def remove_node(self, target_node_data):
Add docstring

2022-02-15 00:01 UTC, pinnheads commented on DS/linked_list.py
> +    def remove_node(self, target_node_data):
Done

2022-02-15 00:01 UTC, pinnheads commented on DS/linked_list.py
> +        raise Exception("Node with data '%s' not found" % target_node_data)
Created a new method

2022-02-15 00:01 UTC, pinnheads commented on DS/linked_list.py
> +class LinkedList(object):
Done

2022-02-15 00:02 UTC, pinnheads commented on Algo/Search/search.py
> +
Done

2022-02-15 00:03 UTC, pinnheads commented on Algo/Search/search.py
> +    beg, end = 0, len(arr) - 1
Changed it to start

2022-02-15 00:12 UTC, pinnheads commented
@avinash-rath Can you review this once again? I have committed the changes requested.

2022-02-16 04:28 UTC, avinash-rath requested changes

2022-02-16 04:28 UTC, avinash-rath commented on DS/linked_list.py
> +                raise Exception("Previous node is null!")
This exception is raised when the index in the args is greater than the length of the LL. The exception method should mention this. On a side note, you can check for this beforehand and raise an exception. No need to iterate through the whole LL.

2022-02-16 04:28 UTC, avinash-rath commented on DS/linked_list.py
> +        if index == 0 or self.head == None:
if I make a call as such, 
insert(12, None) // this should throw an error saying, such index does not exist in the LL.
however, in the current scenario, it'll just add a node at position 0.

2022-02-16 04:28 UTC, avinash-rath commented on DS/linked_list.py
> +    def ll_length(self):
You can just count the length while inserting/deleting nodes and maintain a private class variable. Then make a getter for it. This would sidestep the O(n) pass through the LL every time this method is called. Kind of the concept of how caching works

2022-02-16 23:39 UTC, pinnheads commented on DS/linked_list.py
> +        if index == 0 or self.head == None:
I have added a new check for the same.

2022-02-24 23:03 UTC, pinnheads commented
@avinash-rath can you check this again I have committed the requested changes?

2022-09-16 16:38 UTC, closed without merging